function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;');}
const dash=(v)=>v?esc(v):'—';
const para=(v)=>String(v || '—').split('\n').map((line)=>`<p>${esc(line || ' ')}</p>`).join('');

function renderHandoverCompletionCertificatePdf({ project, certificate, headerParties = [] }) {
  const c = certificate || {};
  const title = c.certificate_title || 'PROJECT COMPLETION CERTIFICATE';
  const logoDataUrl = c.logo_data_url || '';
  const logoHtml = logoDataUrl ? `<img src="${esc(logoDataUrl)}" alt="Silver Foundation Logo"/>` : '<div class="logo-slot">SFCC</div>';
  const bodyText = c.certificate_body_text || `The project works have been completed in accordance with the approved internal scope records, specifications, drawings, approvals, and applicable contract requirements. This controlled QMS record confirms internal completion status, closeout documentation readiness, and listed outstanding items or exceptions before final external handover evidence is retained.`;
  const parties = Array.isArray(headerParties) ? headerParties.slice(0, 4) : [];
  const headerCells = parties.map((party) => {
    const logo = party?.logoDataUrl ? `<img src="${esc(party.logoDataUrl)}" alt="${esc(party?.roleLabel || party?.label || 'Logo')}"/>` : '<div class="party-logo-slot"></div>';
    return `<div class="party-cell"><div class="party-logo">${logo}</div><div class="party-name">${dash(party?.name || party?.roleLabel || party?.label)}</div></div>`;
  }).join('');
  const metaRows = [
    ['Project Name', project?.name || c.project_name, 'Project Code', project?.code || c.project_code],
    ['Client / Employer', project?.client || c.client_name, 'Main Contractor', c.contractor_name || 'Silver Foundation Contracting Company'],
    ['Location', project?.location || c.site_location, 'Contract No.', c.contract_number],
    ['Completion Certificate No.', c.certificate_title || title, 'Certificate Date', c.certificate_issue_date],
    ['Handover Status', c.handover_status, 'Issue Status', Number(c.certificate_issued || 0) ? 'Issued' : 'Draft'],
    ['Internal Approval Status', c.certificate_approved || 'Not Approved', 'Signed Evidence Ref.', c.signed_evidence_reference],
    ['Prepared By', c.prepared_by, 'Approved Internally By', c.internally_approved_by],
  ].map(([a,b,c1,d])=>`<tr><th>${esc(a)}</th><td>${dash(b)}</td><th>${esc(c1)}</th><td>${dash(d)}</td></tr>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"/><style>
  @page{size:A4 portrait;margin:12mm 11mm 13mm}
  *{box-sizing:border-box} body{margin:0;font-family:Arial,Helvetica,sans-serif;color:#1f2933;font-size:10.5pt;line-height:1.38;background:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  .doc{width:100%;max-width:190mm;margin:0 auto}.header{display:grid;grid-template-columns:34mm 1fr 36mm;gap:5mm;align-items:center;border-bottom:1.5pt solid #a9762a;padding-bottom:4mm;margin-bottom:4mm}.brand img{max-width:32mm;max-height:18mm;object-fit:contain}.logo-slot{border:1pt solid #d6c8af;color:#a9762a;font-weight:700;text-align:center;padding:5mm 0}.company{text-align:center}.company h1{margin:0;color:#2a2b2a;font-size:16pt;letter-spacing:.02em}.company p{margin:1mm 0 0;color:#6b6255;font-size:9pt}.doc-meta{text-align:right;font-size:8.5pt;color:#4b5563}.title{margin:0 0 4mm;text-align:center;color:#2a2b2a;font-size:14pt;font-weight:700;text-transform:uppercase;letter-spacing:.03em}.party-header{display:grid;grid-template-columns:repeat(4,1fr);gap:2mm;margin-bottom:4mm}.party-cell{border:1pt solid #ded2bd;border-radius:2mm;padding:2mm;text-align:center;min-height:17mm}.party-logo img{max-height:8mm;max-width:100%;object-fit:contain}.party-logo-slot{height:8mm}.party-name{margin-top:1mm;font-size:8pt;color:#4b5563}.section{break-inside:avoid;margin-top:4mm}.section h2{margin:0 0 1.5mm;border-left:3pt solid #a9762a;padding-left:2mm;color:#2a2b2a;font-size:10.5pt;text-transform:uppercase;letter-spacing:.02em}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1pt solid #cfc6b8;padding:2mm 2.2mm;vertical-align:top;overflow-wrap:anywhere}th{width:22%;background:#f3eee5;color:#3f3f3f;font-size:8.5pt;font-weight:700;text-align:left}td{font-size:9pt;font-weight:400}.text-box{border:1pt solid #cfc6b8;padding:3mm;min-height:18mm;overflow-wrap:anywhere;white-space:normal}.text-box p{margin:0 0 2mm}.text-box p:last-child{margin-bottom:0}.summary-grid{display:grid;grid-template-columns:1fr 1fr;gap:3mm}.signature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:3mm;margin-top:5mm}.signature{border:1pt solid #cfc6b8;min-height:31mm;padding:3mm}.signature h3{margin:0 0 7mm;font-size:9pt;color:#2a2b2a}.line{border-bottom:1pt solid #6b7280;height:7mm;margin-bottom:2mm}.footer{margin-top:6mm;border-top:1pt solid #cfc6b8;padding-top:2mm;text-align:center;color:#6b7280;font-size:8pt}
  </style></head><body><main class="doc"><header class="header"><div class="brand">${logoHtml}</div><div class="company"><h1>SILVER FOUNDATION CONTRACTING COMPANY</h1><p>Quality Management System · Controlled Closeout Document</p></div><div class="doc-meta">A4 Portrait<br/>Printed: ${esc(new Date().toISOString().slice(0,10))}<br/>Status: ${Number(c.certificate_issued || 0) ? 'Issued' : 'Draft'}</div></header><h1 class="title">${esc(title)}</h1>${headerCells ? `<div class="party-header">${headerCells}</div>` : ''}<section class="section"><h2>Project & Certificate Metadata</h2><table>${metaRows}</table></section><section class="section"><h2>Certificate Body Text</h2><div class="text-box">${para(bodyText)}</div></section><section class="section"><h2>Closeout Summaries</h2><div class="summary-grid"><div><h2>Scope Completed Summary</h2><div class="text-box">${para(c.scope_completed_summary)}</div></div><div><h2>Outstanding Items / Exceptions</h2><div class="text-box">${para(c.outstanding_items)}</div></div><div><h2>Snag Status Summary</h2><div class="text-box">${para(c.snag_status_summary)}</div></div><div><h2>Remarks</h2><div class="text-box">${para(c.certificate_remarks)}</div></div></div></section><section class="section"><h2>Prepared / Approved</h2><div class="signature-grid"><div class="signature"><h3>Prepared By</h3><div class="line"></div><p>${dash(c.prepared_by)}</p><p>Date: ${dash(c.certificate_issue_date)}</p></div><div class="signature"><h3>Approved Internally By</h3><div class="line"></div><p>${dash(c.internally_approved_by)}</p><p>Status: ${dash(c.certificate_approved || 'Not Approved')}</p></div><div class="signature"><h3>Signed Evidence</h3><div class="line"></div><p>Reference: ${dash(c.signed_evidence_reference)}</p><p>Upload Status: ${Number(c.certificate_uploaded || 0) ? 'Uploaded' : 'Not Recorded'}</p></div></div></section><footer class="footer">3025 Ar Rajmiyah - 6170 Al Maseef Dist. | Postal Code 124665 | Riyadh · +966 92 003 3605 · info@silver-foundation.com · www.silver-foundation.com</footer></main></body></html>`;
}
module.exports = { renderHandoverCompletionCertificatePdf };
